apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: collector-app
automountServiceAccountToken: false # On verrouille au niveau du compte
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: collector-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: collector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: postgres-sa # On lie le compte sécurisé
      containers:
        - name: postgres
          image: postgres:15-alpine
          # Bloc Resources réaligné pour l'analyse Sonar
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: POSTGRES_DB
              value: catalog_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db-password
          ports:
            - containerPort: 5432