---
# 1. CATALOG SERVICE (Backend Spring Boot)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: collector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      automountServiceAccountToken: false  
      containers:
        - name: catalog-service
          image: collector-catalog:latest
          imagePullPolicy: Never
          resources:                       
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"              
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "collector_db_user"
            - name: DB_PASSWORD
              value: "CatalogDbSecret2024!" 
            - name: KAFKA_BOOTSTRAP
              value: "collector-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://localhost:8080/auth/realms/collector-realm"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8080/auth/realms/collector-realm/protocol/openid-connect/certs"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: collector-app
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
# 2. NOTIFICATION SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: collector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      automountServiceAccountToken: false  
      containers:
        - name: notification-service
          image: collector-notification:latest
          imagePullPolicy: Never
          resources:                       
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: KAFKA_BOOTSTRAP
              value: "collector-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"

---
# 3. COLLECTOR FRONTEND (Nginx/React)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-front
  namespace: collector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-front
  template:
    metadata:
      labels:
        app: collector-front
    spec:
      automountServiceAccountToken: false  
      containers:
        - name: collector-front
          image: collector-front:v2
          imagePullPolicy: Never
          resources:                      
            requests:
              memory: "64Mi"              
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
---
# 4. EXPOSITION PUBLIQUE 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collector-ingress
  namespace: collector-app
spec:
  ingressClassName: nginx 
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collector-front
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 8081