server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.collector.notification.dto"
        spring.json.value.default.type: "com.collector.notification.dto.ArticleDTO"

  mail:
    host: maildev-service
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    org.springframework.mail: DEBUG
    com.collector.notification: DEBUG